# Numpy

## Импорт библиотеки

Способ 1

In [ ]:
pip install numpy

In [1]:
import numpy

In [3]:
l = [1,2,3]

In [4]:
type(l)

list

In [4]:
numpy.array([1,2,3])

NameError: name 'numpy' is not defined

Способ 2 - Рекомендуемый

In [1]:
import numpy as np

In [2]:
np.empty([1,2])

array([[-2.31584178e+077,  3.11109703e+231]])

In [5]:
np_ar = np.array([1,2,3])

In [6]:
type(np_ar)

numpy.ndarray

Способ 3

In [10]:
from numpy import *

In [11]:
array([1,2,3])

array([1, 2, 3])

## Демо скорости Numpy

In [7]:
l = [i for i in range(100000)]

In [9]:
l[-1:]

[99999]

In [10]:
%%timeit
[i+2 for i in l]

7.1 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
np_l = np.array(l)

In [12]:
type(np_l)

numpy.ndarray

In [13]:
%%timeit
np_l + 2

39.4 µs ± 4.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


1ms = 1000 µs (microseconds)

In [14]:
np_l[:5], (np_l+2)[:5], [i+2 for i in l[:5]]

(array([0, 1, 2, 3, 4]), array([2, 3, 4, 5, 6]), [2, 3, 4, 5, 6])

## Векторизация и трансляция

### Векторизация

Сравнение умножения двух векторов используя Python последовательности

In [15]:
a = range(10)
b = range(20,40,2)

In [16]:
list(a), list(b)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

Чистый Python

In [24]:
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

In [18]:
c

[0, 22, 48, 78, 112, 150, 192, 238, 288, 342]

Numpy

In [ ]:
a = np.array(a)
b = np.array(b)

In [25]:
c = a * b 

In [20]:
c

array([  0,  22,  48,  78, 112, 150, 192, 238, 288, 342])

### Broadcasting

In [26]:
a = np.array([1,2,3,4])
a * 2 - 10

array([-8, -6, -4, -2])

## Массивы

Инициализация, характеристики, копирование, типы данных, reshape, фильтрация, сортировка

Инициализация массивов

In [27]:
a = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [29]:
?np.array

In [30]:
a = np.array([1,2,3,4,5])

In [31]:
a

array([1, 2, 3, 4, 5])

Array всегда содержит элементы одного типа.

In [32]:
a = np.array([1, 'abc', True])

In [33]:
a

array(['1', 'abc', 'True'], dtype='<U21')

In [34]:
a = np.array([1, 'abc', True], dtype=float)

ValueError: could not convert string to float: 'abc'

In [43]:
a = np.array([[20, True, 1.5],[20, True, 1.5]])

In [44]:
a

array([[20. ,  1. ,  1.5],
       [20. ,  1. ,  1.5]])

Характеристики массивов

In [39]:
a.sum()

22.5

In [37]:
type(a)

numpy.ndarray

In [49]:
a.shape

(2, 3)

In [46]:
a.size

6

In [47]:
a.ndim

2

Не помните все характериситики объекта? Вызовите docstring

In [50]:
a?

Размер каждого элемента массива в байтах

In [51]:
a.itemsize

8

Значит, размер всего массива - следующий

In [52]:
a.size * a.itemsize

48

In [53]:
a.nbytes

48

Двумерные массивы

In [64]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])

In [65]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [59]:
b.dtype

dtype('float64')

In [66]:
b = np.array(b, dtype=int)

In [67]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=complex)

In [69]:
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

## Другие функции для создания массивов

In [4]:
a = np.zeros((3, 5))

In [5]:
a.shape

(3, 5)

In [6]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
l = []

for i in range(100):
    l.append([1,2,3])

In [11]:
np.array(l)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1,

Функция empty() создает массив без его заполнения. Исходное содержимое случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится).

In [24]:
np.random.seed(41)

In [26]:
np.empty((3, 3))

array([[ 2.00000000e+000, -2.32036364e+077,  2.47032823e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [13]:
# Массив из одних и тех же цифр
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [16]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [15]:
# Такой же формы, но заполнить некоторым числом (full_like)
np.full_like(a, 4)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [18]:
?np.random

In [30]:
np.random.seed(32)

In [29]:
# Случайные числа
np.random.rand(4, 2)

array([[0.24851013, 0.44997542],
       [0.4109408 , 0.26029969],
       [0.87039569, 0.18503993],
       [0.01966143, 0.95325203]])

In [31]:
# Случайные числа
np.random.rand(4,2)

array([[0.85888927, 0.37271115],
       [0.55512878, 0.95565655],
       [0.7366696 , 0.81620514],
       [0.10108656, 0.92848807]])

In [32]:
# Случайные целые числа в диапазоне
np.random.randint(-4, 8, size=(3,3))

array([[ 0,  7, -3],
       [-1, -3, -2],
       [-1,  4,  6]])

Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), только вместо списков она возвращает массивы, и принимает не только целые значения.

In [42]:
list(range(10,30,5))

[10, 15, 20, 25]

In [33]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [40]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

При использовании arange() с аргументами типа float и необходимости задать кол-во элементов - используем функцию linspace(), которая вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов.

In [38]:
np.linspace(0, 2, 9) # 9 чисел от 0 до 2 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
np.linspace(0, 1, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [44]:
np.linspace(0, 0.9, 10) # 9 чисел от 0 до 2 включительно

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

Ещё один способ создать массив

In [47]:
def f1(i, j):
    return 3 * i + j

In [48]:
np.fromfunction(f1, (3, 4))

array([[0., 1., 2., 3.],
       [3., 4., 5., 6.],
       [6., 7., 8., 9.]])

In [49]:
np.fromfunction(f1, (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Базовые операции над массивами

Печать массивов

In [50]:
a = np.arange(0, 3000, 1)

In [55]:
a

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [56]:
a.__str__()

'[   0    1    2 ... 2997 2998 2999]'

In [51]:
print(a)

[   0    1    2 ... 2997 2998 2999]


In [57]:
a[:10], a[:100]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]))

Можем настраивать формат печати, чтоб увидеть больше элементов массива.

In [74]:
np.set_printoptions(threshold=100)

In [76]:
a[100:200]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

Посмотрим, какие настройки мы можем менять.

In [80]:
np.set_printoptions?

In [79]:
31231e431231

10000.0

In [ ]:
0.123

## Индексация массивов

In [81]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [82]:
# Получить конкретный элемент [r, c]
a[1, 5]

13

In [84]:
a[1][5]

13

In [86]:
# Получить строку
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [88]:
a[0, :5]

array([1, 2, 3, 4, 5])

In [85]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [87]:
# Получить колонку
a[:, 2]

array([ 3, 10])

In [90]:
# Более изощрённый запрос [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [89]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [91]:
a[1,5] = 20

In [92]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [93]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D пример

In [94]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [95]:
# Получить конкретный элемент: идём снаружи вовнутрь
b[0,1,1]

4

In [97]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [102]:
# Поменять значение так нельзя
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [99]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [100]:
#  А так можно
b[:,1,:] = 12

In [101]:
b

array([[[ 1,  2],
        [12, 12]],

       [[ 5,  6],
        [12, 12]]])

In [ ]:
#  И так можно
b[:,1,:] = [[1,2],[11,12]]

In [ ]:
b

## Реорганизация массивов

In [103]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
before.size

8

In [105]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [108]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [110]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Копирование массивов

In [113]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(b, a)

[100   2   3] [100   2   3]


In [114]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b, a)

[100   2   3] [1 2 3]


In [ ]:
a.copy(), np.copy(a)

## Математика

In [115]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [116]:
a + 2

array([3, 4, 5, 6])

In [117]:
a - 2

array([-1,  0,  1,  2])

In [118]:
a * 2

array([2, 4, 6, 8])

In [119]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [120]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [121]:
a + [1,0,1,0]

array([2, 2, 4, 4])

In [122]:
a ** 2

array([ 1,  4,  9, 16])

In [123]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [124]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

Больше функций тут https://docs.scipy.org/doc/numpy/reference/routines.math.html